version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    image: 3xtr-frontend
    container_name: frontend
    ports:
      - "127.0.0.1:3000:80"
    restart: unless-stopped
