import { reactive } from 'vue';

/**
 * Reactive language store with translations for English and Russian.
 * It remembers the selected language in localStorage (key: 'lang').
 */
const savedLang = localStorage.getItem('lang') || 'en';

const messages = {
  en: {
    // General UI strings
    welcome: 'Welcome back',
    agentsSubtitle: 'Build, test, and deploy your custom agents.',
    createAgent: 'Create Agent',
    noAgents: 'No agents created yet',
    clickToCreate: "Click 'Create Agent' to get started",
    statusPublished: 'Published',
    statusDraft: 'Draft',
    chats: 'Chats',
    noChats: 'No chats yet',
    selectChat: 'Select a chat to view',
    account: 'Account',
    profile: 'Profile',
    teamManagement: 'Team Management',
    dangerZone: 'Danger Zone',
    transferOwnership: 'Transfer Ownership',
    deleteAccount: 'Delete Account',
    lightMode: 'Light mode',
    darkMode: 'Dark mode',
    classic: 'Classic',
    emerald: 'Emerald',
    wine: 'Wine',
    graphite: 'Graphite',
    sapphire: 'Sapphire',
    violet: 'Violet',
    // Chat status labels
    attention: 'Requires Attention',
    live: 'Live',
    paused: 'Paused',
    resolved: 'Resolved',
    idle: 'Idle',
    // Sandbox messages
    send: 'Send',
    typeMessage: 'Type a message…',
    // Coming soon text
    comingSoon: 'This tab is coming soon.',
    all: 'All',
    // Additional navigation and account strings
    agents: 'Agents',
    knowledge: 'Knowledge',
    logout: 'Log out',
    owner: 'Owner',
    accountSettings: 'Account Settings',
    manageProfileTeamBilling: 'Manage your profile, team and billing.',
    backToAll: 'Back to all',
    addFile: 'Add File',
    pressInterfere: 'Press "Interfere" to start typing…',
    dropHere: 'Drop a file here or click to browse',
    dragAnother: 'Drag another file to replace',
    pendingInvitation: 'Pending invitation',
    cancelInvite: 'Cancel invite',
    edit: 'Edit',
    delete: 'Delete',
    updateFile: 'Update',
    // 404 page
    pageNotFound: 'Page not found',
    goHome: 'Go to dashboard',
    // Knowledge & groups
    knowledgeTitle: 'Knowledge Bases',
    knowledgeSubtitle: 'Organize your knowledge groups.',
    createGroup: 'Create Group',
    noKnowledgeGroups: 'No knowledge groups yet',
    clickCreateGroup: "Click 'Create Group' to add your first group.",
    groupEmpty: 'This group is empty',
    clickAddFile: "Click 'Add File' to add your first knowledge source.",
    files: 'Files',
    name: 'Name',
    description: 'Description',
    type: 'Type',
    details: 'Details',
    unknownFileType: 'Unknown file type.',
    openInNewTab: 'Open in new tab',
    close: 'Close',
    add: 'Add',
    uploadFile: 'Upload File',
    text: 'Text',
    link: 'Link',
    addKnowledgeSource: 'Add New Knowledge Source',
    chooseType: 'Choose the type of content you want to add.',
    textContent: 'Text Content',
    url: 'URL',
    urlDescription: 'Description',
    groupName: 'Group Name',
    groupDescription: 'A short description of what this group contains.',
    createKnowledgeGroup: 'Create Knowledge Group',
    createGroupAction: 'Create Group',
    // Account
    profileSection: 'Profile',
    teamManagementSection: 'Team Management',
    planLabel: 'Plan',
    noTeamMembers: 'No team members added yet.',
    inviteMember: 'Invite Member',
    inviteNewMember: 'Invite New Team Member',
    inviteDesc: 'Fill in the details to invite a new collaborator.',
    fullName: 'Full Name',
    email: 'Email',
    role: 'Role',
    admin: 'Admin',
    operator: 'Operator',
    readOnly: 'Read-only',
    invite: 'Invite',
    cancel: 'Cancel',
    dangerZoneSection: 'Danger Zone',
    transferOwnershipAction: 'Transfer Ownership',
    deleteAccountAction: 'Delete Account',
    deleteAccountConfirm: 'Are you sure you want to delete your account?',
    // Agent form
    editAgent: 'Edit Agent',
    createAgentHeader: 'Create a New Agent',
    loadingFormData: 'Loading form data...',
    agentName: 'Agent Name',
    personality: 'Personality',
    formal: 'Formal',
    friendly: 'Friendly',
    witty: 'Witty',
    model: 'Model',
    knowledgeBases: 'Knowledge Bases',
    noKnowledgeAvailable: 'No knowledge groups available.',
    systemPrompt: 'System Prompt',
    published: 'Published',
    draft: 'Draft',
    deleteAgent: 'Delete Agent',
    saveAgent: 'Save Agent',
    // Knowledge file form
    nameLabel: 'Name',
    descriptionLabel: 'Description',
    textContentLabel: 'Text Content',
    urlLabel: 'URL',
    urlDescLabel: 'Description',
    // Table column headers
    modelLabel: 'Model',
    channels: 'Channels',
    knowledgeColumn: 'Knowledge',
    statusColumn: 'Status',
    actions: 'Actions',
    // Invite form
    roleAdmin: 'Admin',
    roleOperator: 'Operator',
    roleReadOnly: 'Read-only',
    // Chat actions and notifications
    resolve: 'Resolve',
    end: 'End',
    interfere: 'Interfere',
    assignedAgent: 'Agent',
    returnToAgent: 'Return to Agent',
    controlReturned: 'Control returned to agent',
    messageSent: 'Message sent',
    messageSendFailed: 'Failed to send message',
    joinedChat: 'Joined the chat',
    failedInterfere: 'Failed to interfere',
    issueResolvedMsg: 'Issue resolved',
    failedResolve: 'Failed to resolve',
    chatEndedMsg: 'Chat ended',
    failedEndChat: 'Failed to end chat',
    nowLabel: 'now',
    minute: 'minute',
    minutes: 'minutes',
    hour: 'hour',
    hours: 'hours',
    day: 'day',
    days: 'days',
    unsavedChanges: 'You have unsaved changes. Are you sure you want to close?',
    // Agent detail tabs
    analytics: 'Analytics',
    integrations: 'Integrations',
    testSandbox: 'Test Sandbox',
    info: 'Info',
    // Dashboard & navigation
    dashboardSubtitle: "Let's build some amazing agents today.",
    navAgents: 'Agents',
    navAgentsDesc: 'Build and customize your agents',
    navChats: 'Chats',
    navChatsDesc: 'View and manage all your chats',
    navKnowledge: 'Knowledge Base',
    navKnowledgeDesc: 'Store useful info for your agents',
    navAccount: 'Account',
    navAccountDesc: 'Manage your account settings',
    createFirstAgent: 'Create your first agent here!',
    createFirstAgentSubtitle: 'Easier than you think',
    chat: 'Chat',
    agentInfoTitle: 'Agent information',
    // Toast messages
    roleUpdated: 'Role updated',
    roleUpdateFailed: 'Failed to update role',
    invitationCancelled: 'Invitation cancelled',
    invitationCancelFailed: 'Failed to cancel invitation',
    accountDeletedMsg: 'Account deleted',
    accountDeleteFailed: 'Failed to delete account',
    transferComingSoon: 'Transfer ownership feature coming soon!'
  },
  ru: {
    welcome: 'С возвращением',
    agentsSubtitle: 'Создавайте, тестируйте и развёртывайте своих агентов.',
    createAgent: 'Создать агента',
    noAgents: 'Агенты пока не созданы',
    clickToCreate: "Нажмите 'Создать агента', чтобы начать",
    statusPublished: 'Опубликован',
    statusDraft: 'Черновик',
    chats: 'Чаты',
    noChats: 'Пока нет чатов',
    selectChat: 'Выберите чат, чтобы просмотреть',
    account: 'Аккаунт',
    profile: 'Профиль',
    teamManagement: 'Управление командой',
    dangerZone: 'Опасная зона',
    transferOwnership: 'Передать владение',
    deleteAccount: 'Удалить аккаунт',
    lightMode: 'Светлая тема',
    darkMode: 'Тёмная тема',
    classic: 'Классическая',
    emerald: 'Изумруд',
    wine: 'Бордовая',
    graphite: 'Графит',
    sapphire: 'Сапфир',
    violet: 'Фиолетовая',
    attention: 'Требует внимания',
    live: 'Активный',
    paused: 'На паузе',
    resolved: 'Решён',
    idle: 'Закрыт',
    send: 'Отправить',
    typeMessage: 'Введите сообщение…',
    comingSoon: 'Эта вкладка скоро появится.',
    all: 'Все',
    // Additional navigation and account strings
    agents: 'Агенты',
    knowledge: 'Знания',
    logout: 'Выйти',
    owner: 'Владелец',
    accountSettings: 'Настройки аккаунта',
    manageProfileTeamBilling: 'Управляйте профилем, командой и оплатой.',
    backToAll: 'Назад ко всем',
    addFile: 'Добавить файл',
    pressInterfere: 'Нажмите «Вмешаться», чтобы начать писать…',
    dropHere: 'Перетащите файл сюда или нажмите, чтобы выбрать',
    dragAnother: 'Перетащите другой файл, чтобы заменить',
    pendingInvitation: 'Приглашение отправлено',
    cancelInvite: 'Отменить приглашение',
    edit: 'Редактировать',
    delete: 'Удалить',
    updateFile: 'Обновить',
    // 404 page
    pageNotFound: 'Страница не найдена',
    goHome: 'На главную',
    knowledgeTitle: 'Базы знаний',
    knowledgeSubtitle: 'Управляйте группами знаний.',
    createGroup: 'Создать группу',
    noKnowledgeGroups: 'Группы знаний ещё не созданы',
    clickCreateGroup: "Нажмите «Создать группу», чтобы добавить первую.",
    groupEmpty: 'В этой группе пока нет файлов',
    clickAddFile: "Нажмите «Добавить файл», чтобы загрузить первый источник.",
    files: 'Файлы',
    name: 'Название',
    description: 'Описание',
    type: 'Тип',
    details: 'Детали',
    unknownFileType: 'Неизвестный тип файла.',
    openInNewTab: 'Открыть в новой вкладке',
    close: 'Закрыть',
    add: 'Добавить',
    uploadFile: 'Загрузить файл',
    text: 'Текст',
    link: 'Ссылка',
    addKnowledgeSource: 'Добавить источник знаний',
    chooseType: 'Выберите тип содержимого для добавления.',
    textContent: 'Текст',
    url: 'Ссылка',
    urlDescription: 'Описание',
    groupName: 'Название группы',
    groupDescription: 'Краткое описание содержимого группы.',
    createKnowledgeGroup: 'Создать группу знаний',
    createGroupAction: 'Создать группу',
    // Account
    profileSection: 'Профиль',
    teamManagementSection: 'Управление командой',
    planLabel: 'Тариф',
    noTeamMembers: 'Участники команды ещё не добавлены.',
    inviteMember: 'Пригласить участника',
    inviteNewMember: 'Пригласить нового участника',
    inviteDesc: 'Заполните данные, чтобы пригласить нового коллегу.',
    fullName: 'Полное имя',
    email: 'Email',
    role: 'Роль',
    admin: 'Администратор',
    operator: 'Оператор',
    readOnly: 'Только чтение',
    invite: 'Пригласить',
    cancel: 'Отмена',
    dangerZoneSection: 'Опасная зона',
    transferOwnershipAction: 'Передать владение',
    deleteAccountAction: 'Удалить аккаунт',
    deleteAccountConfirm: 'Вы уверены, что хотите удалить аккаунт?',
    // Agent form
    editAgent: 'Редактировать агента',
    createAgentHeader: 'Создать нового агента',
    loadingFormData: 'Загрузка данных формы...',
    agentName: 'Имя агента',
    personality: 'Характер',
    formal: 'Формальный',
    friendly: 'Дружелюбный',
    witty: 'Остроумный',
    model: 'Модель',
    knowledgeBases: 'Базы знаний',
    noKnowledgeAvailable: 'Нет доступных групп знаний.',
    systemPrompt: 'Системный запрос',
    published: 'Опубликован',
    draft: 'Черновик',
    deleteAgent: 'Удалить агента',
    saveAgent: 'Сохранить агента',
    // Knowledge file form
    nameLabel: 'Название',
    descriptionLabel: 'Описание',
    textContentLabel: 'Текст',
    urlLabel: 'Ссылка',
    urlDescLabel: 'Описание',
    // Table column headers
    modelLabel: 'Модель',
    channels: 'Каналы',
    knowledgeColumn: 'Знания',
    statusColumn: 'Статус',
    actions: 'Действия',
    // Invite form
    roleAdmin: 'Администратор',
    roleOperator: 'Оператор',
    roleReadOnly: 'Только чтение',
    // Chat actions and notifications
    resolve: 'Решить',
    end: 'Завершить',
    interfere: 'Вмешаться',
    assignedAgent: 'Агент',
    returnToAgent: 'Вернуть агенту',
    controlReturned: 'Управление возвращено агенту',
    messageSent: 'Сообщение отправлено',
    messageSendFailed: 'Не удалось отправить сообщение',
    joinedChat: 'Вы присоединились к чату',
    failedInterfere: 'Не удалось вмешаться',
    issueResolvedMsg: 'Проблема решена',
    failedResolve: 'Не удалось решить проблему',
    chatEndedMsg: 'Чат завершён',
    failedEndChat: 'Не удалось завершить чат',
    nowLabel: 'сейчас',
    minute: 'минута',
    minutes: 'минуты',
    hour: 'час',
    hours: 'часов',
    day: 'день',
    days: 'дней',
    unsavedChanges: 'Есть несохранённые изменения. Закрыть без сохранения?',
    // Agent detail tabs
    analytics: 'Аналитика',
    integrations: 'Интеграции',
    testSandbox: 'Песочница',
    info: 'Инфо',
    // Dashboard & navigation
    dashboardSubtitle: 'Создавайте невероятных агентов уже сегодня.',
    navAgents: 'Агенты',
    navAgentsDesc: 'Создавайте и настраивайте своих агентов',
    navChats: 'Чаты',
    navChatsDesc: 'Просматривайте и управляйте вашими чатами',
    navKnowledge: 'База знаний',
    navKnowledgeDesc: 'Храните полезную информацию для агентов',
    navAccount: 'Аккаунт',
    navAccountDesc: 'Управляйте настройками аккаунта',
    createFirstAgent: 'Создайте своего первого агента здесь!',
    createFirstAgentSubtitle: 'Это проще, чем вы думаете',
    chat: 'Чат',
    agentInfoTitle: 'Информация об агенте',
    // Toast messages
    roleUpdated: 'Роль обновлена',
    roleUpdateFailed: 'Не удалось обновить роль',
    invitationCancelled: 'Приглашение отменено',
    invitationCancelFailed: 'Не удалось отменить приглашение',
    accountDeletedMsg: 'Аккаунт удалён',
    accountDeleteFailed: 'Не удалось удалить аккаунт',
    transferComingSoon: 'Функция передачи владения скоро будет доступна!'
  }
};

// создаём reactive‑объект отдельно, чтобы внутри функций обращаться к нему напрямую
const store = reactive({
  current: savedLang,
  messages,
  setLang(lang) {
    store.current = lang;
    localStorage.setItem('lang', lang);
  },
  // Стрелочная функция не зависит от this и использует замыкание на store
  t: (key) => {
    const dict = store.messages[store.current] || store.messages.en;
    return dict[key] ?? store.messages.en[key] ?? key;
  }
});

export const langStore = store;
export default langStore;
